"""
Live demo for agentmemory.

Three things this UI proves:
  1. Pull, never push: the user must click "Build context" before any
     past memory enters the prompt. Nothing is silently injected.
  2. Show the trace: every summary displays the event ids and the exact
     prompt text that was sent to Claude.
  3. Real deletes: every event has a "Delete" button that removes the
     row entirely, no tombstone, no derived artifact.

Deploy:
  - Streamlit Community Cloud: connect this repo, app file = examples/streamlit/app.py
  - HuggingFace Spaces: pick the Streamlit SDK, point to this file
  - Local: `pip install -r requirements.txt && streamlit run app.py`

API key:
  - Provide ANTHROPIC_API_KEY in the sidebar (or set env var).
  - Optional: leave blank to run in dry-run mode (no Claude calls; the
    summarizer returns a stub so reviewers can poke around without
    spending tokens).
"""

from __future__ import annotations

import os
import time

import streamlit as st

from agentmemory_py import (
    EpisodicStore,
    OnDemandSummarizer,
    MemoryDriftWatcher,
)

# ---------- page setup ----------

st.set_page_config(
    page_title="agentmemory live demo",
    page_icon="🧠",
    layout="wide",
)

st.title("agentmemory")
st.caption(
    "Honest pull-model memory for LLM agents. The OSS alternative to "
    "Anthropic Dreaming, with real deletes and no silent context injection."
)

# ---------- session state ----------

if "store" not in st.session_state:
    st.session_state.store = EpisodicStore()
if "watcher" not in st.session_state:
    st.session_state.watcher = MemoryDriftWatcher(
        window_size=20, drop_threshold=0.15
    )
if "last_summary" not in st.session_state:
    st.session_state.last_summary = None
if "last_trace" not in st.session_state:
    st.session_state.last_trace = None

store: EpisodicStore = st.session_state.store
watcher: MemoryDriftWatcher = st.session_state.watcher

# ---------- sidebar: API key + reset ----------

with st.sidebar:
    st.header("Setup")
    api_key = st.text_input(
        "ANTHROPIC_API_KEY",
        type="password",
        value=os.environ.get("ANTHROPIC_API_KEY", ""),
        help="Leave blank to run in dry-run mode (no Claude calls).",
    )
    model = st.selectbox(
        "Claude model",
        options=[
            "claude-3-5-haiku-latest",
            "claude-3-5-sonnet-latest",
            "claude-3-opus-latest",
        ],
        index=0,
    )
    max_tokens = st.slider(
        "Summary max_tokens", min_value=50, max_value=800, value=300, step=50
    )
    st.markdown("---")
    if st.button("Reset all memory", use_container_width=True):
        st.session_state.store = EpisodicStore()
        st.session_state.watcher = MemoryDriftWatcher(
            window_size=20, drop_threshold=0.15
        )
        st.session_state.last_summary = None
        st.session_state.last_trace = None
        st.rerun()
    st.markdown("---")
    st.markdown(
        "**[npm](https://www.npmjs.com/package/@mukundakatta/agentmemory)** · "
        "**[GitHub](https://github.com/MukundaKatta/agentmemory)** · "
        "**[Essay](https://dev.to/mukundakatta/why-i-refused-to-build-a-dreaming-clone-for-oss-claude-2631)**"
    )

# ---------- LLM wrapper (Claude or dry-run) ----------


def make_llm(api_key: str, model: str):
    if not api_key:

        def dry_run_llm(prompt: str) -> str:
            return (
                "[DRY RUN] Summary would be generated by Claude here. "
                f"This prompt is {len(prompt)} chars. "
                "Provide ANTHROPIC_API_KEY in the sidebar to enable real calls."
            )

        return dry_run_llm

    try:
        from anthropic import Anthropic
    except ImportError:
        st.error(
            "The `anthropic` Python SDK is not installed. "
            "Run `pip install anthropic` and reload."
        )
        st.stop()

    client = Anthropic(api_key=api_key)

    def claude_llm(prompt: str) -> str:
        try:
            r = client.messages.create(
                model=model,
                max_tokens=max_tokens + 50,
                messages=[{"role": "user", "content": prompt}],
            )
            return r.content[0].text
        except Exception as e:
            return f"[Claude error: {e}]"

    return claude_llm


llm = make_llm(api_key, model)
summarizer = OnDemandSummarizer(llm=llm, max_tokens=max_tokens)

# ---------- main layout ----------

col_left, col_right = st.columns([1, 1])

# === LEFT: append events + retrieve ===

with col_left:
    st.subheader("1. Add an event to memory")
    with st.form("append_form", clear_on_submit=True):
        sid = st.text_input("Session id", value="session-001")
        kind = st.selectbox(
            "Kind",
            options=[
                "user_message",
                "assistant_message",
                "tool_call",
                "tool_result",
                "fact",
            ],
            index=0,
        )
        text = st.text_area(
            "Text",
            placeholder="e.g. user prefers Postgres for the new project",
            height=100,
        )
        submitted = st.form_submit_button("Append", use_container_width=True)
        if submitted and text.strip():
            ev = store.append(session_id=sid, kind=kind, text=text.strip())
            st.success(f"Appended {ev.id} to {sid}")

    st.markdown("---")
    st.subheader("2. Pull context for a new session")
    intent = st.text_input(
        "What is the agent about to do?",
        value="pick a database for a new feature",
        help="Used to retrieve relevant past events.",
    )
    target_session = st.selectbox(
        "Filter by session (optional)",
        options=["(any)"] + store.sessions(),
        index=0,
    )
    top_k = st.slider("Top K events to retrieve", 1, 20, 5)
    if st.button("Retrieve + summarize", type="primary", use_container_width=True):
        events = store.retrieve(
            query=intent,
            session_id=None if target_session == "(any)" else target_session,
            top_k=top_k,
        )
        watcher.record(
            ts=int(time.time() * 1000),
            scores=[e.score or 0 for e in events],
        )
        st.session_state.last_events = events
        with st.spinner("Summarizing with Claude..."):
            result = summarizer.summarize(events, intent)
        st.session_state.last_summary = result.summary
        st.session_state.last_trace = result.trace

# === RIGHT: trace + drift watcher ===

with col_right:
    st.subheader("Last summary (shown before injection)")
    if st.session_state.last_summary is None:
        st.info(
            "No summary yet. Use the left panel to append events, then "
            "click **Retrieve + summarize**."
        )
    else:
        st.markdown(
            f"```text\n{st.session_state.last_summary or '(empty — no events matched)'}\n```"
        )
        with st.expander("Trace: which events fed this summary"):
            st.write("**Event ids used:**", st.session_state.last_trace["event_ids"])
            st.write("**Intent:**", st.session_state.last_trace["intent"])
            st.write("**max_tokens:**", st.session_state.last_trace["max_tokens"])
            st.text_area(
                "Exact prompt sent to Claude",
                value=st.session_state.last_trace["prompt"],
                height=200,
            )

    st.markdown("---")
    st.subheader("Drift watcher")
    state = watcher.state()
    if state["alert"]:
        st.error(f"⚠️ {state['reason']}")
    else:
        st.success(f"✅ {state['reason']}")
    st.caption(
        f"samples={state['samples']} · "
        f"mean recent={state['mean_recent']:.3f} · "
        f"mean baseline={state['mean_baseline']:.3f} · "
        f"drop={state['drop_fraction'] * 100:.1f}%"
    )

# ---------- below: full event log with delete buttons ----------

st.markdown("---")
st.subheader("3. Full memory (real deletes — no tombstones)")
events = store.list()
if not events:
    st.caption("Memory is empty. Append some events above to get started.")
else:
    st.caption(
        f"{len(events)} events across {len(store.sessions())} sessions. "
        "Click **Delete** to hard-remove. The event is gone, not hidden."
    )
    for ev in sorted(events, key=lambda e: e.ts, reverse=True):
        c1, c2, c3, c4, c5 = st.columns([1, 2, 2, 6, 1])
        c1.code(ev.id, language="text")
        c2.text(ev.session_id)
        c3.text(ev.kind)
        c4.text(ev.text[:80] + ("…" if len(ev.text) > 80 else ""))
        if c5.button("Delete", key=f"del_{ev.id}"):
            ok = store.delete_event(ev.id)
            if ok:
                st.toast(f"Deleted {ev.id} (real delete, no tombstone)")
                st.rerun()

# ---------- footer ----------

st.markdown("---")
st.caption(
    "agentmemory v0.2.0 · MIT · "
    "Designed in advance of the Anthropic AI Hackathon (May 26 to June 2, 2026). "
    "Companion essay published May 15."
)
